"""T050 — `factory gate run`, override resolution, `factory override`; T059 workflow.

contracts/gates.md § Override resolution: a failing gate looks for
`bus/orders/<order-id>/override-NN.yaml` with `gate: <id>` at the PR head.
- `class: drift` (from the registry, not the message): an override by `orchestrator`
  or `governor` with a reason turns it into "overridden: <reason>"; counted.
- `class: governor-only`: only `actor: governor`; when `identity.mode` is `verified`,
  the `IdentityPort` must also verify the message; otherwise it stays failed.

The order is the one named by the head branch `wo/<order-id>` (`--head wo/<id>`, or the
PR's head under `--pr N`). Exit 1 on any failure left un-overridden, else 0.

Report (JSON `data` on exit 0, `error.details` on exit 1):
`gates: [{id, class, intents, outcome: pass|fail|overridden, messages, override}]`,
`intents: {<intent id>: [{gate, outcome}]}`, `override_counts: {<gate id>: n}`.
`override` is `{id, actor, reason, verified}` when the outcome is `overridden`.
Every registered CI gate runs (hook rows, which carry `hook_twin_of`, are not CI gates).
Under `--pr N`, one commit status `factory/<gate-id>` per gate is posted on the head.
"""

from __future__ import annotations

import importlib
import json
import re
import shlex
import sys
import types
from pathlib import Path
from typing import Any

import pytest
import yaml

from factory.api import GateContext, GateResult, PullRequest
from factory.bus.models import Message
from factory.cli import exit_codes
from factory.cli.common import DEPS
from factory.gates.registry import load_registry
from tests.fixtures.cli_runner import CliResult, FactoryCli
from tests.fixtures.fake_github import FakeGitHub
from tests.fixtures.repo_builder import BaseHeadPair, RepoBuilder, message, order, yaml_text

pytestmark = pytest.mark.contract

REPO_ROOT = Path(__file__).resolve().parents[4]
WORKFLOW = REPO_ROOT / ".github/workflows/factory-gates.yml"
ORDER_ID = "wo-20261006-gated"
ORDER_DIR = f"bus/orders/{ORDER_ID}"
OTHER = "wo-20261006-merged-earlier"
OTHER_ORDER = f"bus/orders/{OTHER}/order.yaml"
DECISION = "pick-host"
IMMUTABLE = "bus.immutable"
OPEN_OD = "order-blocked-on-open-human-od"
REASON = "Fixture regenerated by the schema migration; content reviewed by hand."


class FakeIdentity:
    """`IdentityPort` stand-in: answers `verified` for every governor message."""

    def __init__(self, verified: bool) -> None:
        self.verified = verified
        self.asked: list[str] = []

    def is_governor_verified(self, message: Message, pr: PullRequest | None) -> bool:
        self.asked.append(message.id)
        return self.verified


@pytest.fixture
def identity(monkeypatch: pytest.MonkeyPatch) -> FakeIdentity:
    fake = FakeIdentity(verified=False)
    monkeypatch.setattr(DEPS, "identity", lambda settings, github: fake)
    return fake


@pytest.fixture
def verified_repo(tmp_path: Path, fake_github: FakeGitHub) -> RepoBuilder:
    return RepoBuilder(tmp_path / "verified", github=fake_github, identity_mode="verified")


def override(nn: int, gate: str, *, actor: str = "orchestrator", **fields: Any) -> dict[str, Any]:
    fields.setdefault("pr", 1)
    data = message("override", order_id=ORDER_ID, gate=gate, actor=actor, reason=REASON, **fields)
    data["id"] = f"{ORDER_ID}.override-{nn:02d}"
    if actor == "governor":
        data.pop("actor_model", None)
    return data


def override_files(*overrides: dict[str, Any]) -> dict[str, str | None]:
    return {
        f"{ORDER_DIR}/override-{o['id'].rsplit('-', 1)[1]}.yaml": yaml_text(o) for o in overrides
    }


def immutable_violation(
    repo: RepoBuilder, *overrides: dict[str, Any], order_dir: str = ORDER_DIR
) -> BaseHeadPair:
    """Work order PR that edits an already-merged bus file (bus.immutable fails)."""
    edited = order(OTHER, goal="Rewrite a merged order after the fact.")
    head: dict[str, str | None] = {
        f"{ORDER_DIR}/order.yaml": yaml_text(order(ORDER_ID)),
        OTHER_ORDER: yaml_text(edited),
    }
    for data in overrides:
        nn = data["id"].rsplit("-", 1)[1]
        head[f"{order_dir}/override-{nn}.yaml"] = yaml_text(data)
    return repo.base_head_pair(
        {OTHER_ORDER: yaml_text(order(OTHER))}, head, head_branch=f"wo/{ORDER_ID}"
    )


def open_od_violation(repo: RepoBuilder, *overrides: dict[str, Any]) -> BaseHeadPair:
    """Work order PR whose order depends on an open governor decision (governor-only)."""
    request = message("decision_request", decision_id=DECISION, blocking=True)
    head: dict[str, str | None] = {
        f"{ORDER_DIR}/order.yaml": yaml_text(order(ORDER_ID, depends_on_decisions=[DECISION])),
        **override_files(*overrides),
    }
    return repo.base_head_pair(
        {f"bus/decisions/{DECISION}/request.yaml": yaml_text(request)},
        head,
        head_branch=f"wo/{ORDER_ID}",
    )


def gate_run(
    factory_cli: FactoryCli,
    repo: RepoBuilder,
    pair: BaseHeadPair,
    *gates: str,
    as_json: bool = True,
) -> CliResult:
    args = ["gate", "run"]
    for gate in gates:
        args += ["--gate", gate]
    args += ["--base", pair.base_sha, "--head", pair.head_branch]
    if as_json:
        args.append("--json")
    return factory_cli(*args, repo=repo.path)


def assert_exit(result: CliResult, expected: int) -> None:
    assert result.exit_code == expected, (
        f"expected exit {expected}, got {result.exit_code}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


def report(result: CliResult) -> dict[str, Any]:
    try:
        envelope = json.loads(result.stdout)
    except ValueError as exc:
        raise AssertionError(
            f"--json stdout is not one JSON document: {result.stdout!r}\nstderr: {result.stderr}"
        ) from exc
    assert isinstance(envelope, dict), envelope
    assert envelope.get("command") == "gate run", envelope
    body = (
        envelope.get("data") if envelope.get("ok") else (envelope.get("error") or {}).get("details")
    )
    assert isinstance(body, dict), envelope
    return body


def entry(body: dict[str, Any], gate_id: str) -> dict[str, Any]:
    matches = [g for g in body.get("gates", []) if g.get("id") == gate_id]
    assert len(matches) == 1, body
    return matches[0]


# --- running gates -------------------------------------------------------------------------


def test_gate_run_runs_every_registered_ci_gate(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo)
    result = gate_run(factory_cli, repo, pair)
    assert result.exit_code in (exit_codes.OK, exit_codes.GATE_FAILURE), result
    body = report(result)
    registry = load_registry()
    expected = {gate.id for gate in registry.gates if gate.hook_twin_of is None}
    assert {g.get("id") for g in body.get("gates", [])} == expected
    for gate in registry.gates:
        if gate.hook_twin_of is None:
            reported = entry(body, gate.id)
            assert reported.get("intents") == gate.intents, reported
            assert reported.get("class") == gate.gate_class, reported
            assert reported.get("outcome") in {"pass", "fail", "overridden"}, reported


class RecordedGates:
    """Stub entrypoint modules for every registered CI gate; records each real call.

    `api.run_gate` imports `gate.module` and reads `gate.function` at call time. The stub
    function replaces the real one on its module (other names in that module stay), or,
    while the module does not exist yet, sits in a stub module in `sys.modules`. Each stub
    returns the outcome set in `failing` plus a message only a real call can produce.
    """

    def __init__(self, monkeypatch: pytest.MonkeyPatch, failing: set[str]) -> None:
        self.calls: list[tuple[str, str, str | None]] = []
        self.failing = failing
        self.gates = [g for g in load_registry().gates if g.hook_twin_of is None]
        stubs: dict[str, types.ModuleType] = {}
        for gate in self.gates:
            function = self._entrypoint(gate.id, list(gate.intents))
            try:
                module = importlib.import_module(gate.module)
            except ImportError:
                module = stubs.setdefault(gate.module, types.ModuleType(gate.module))
                setattr(module, gate.function, function)
            else:
                monkeypatch.setattr(module, gate.function, function, raising=False)
        for name, module in stubs.items():
            monkeypatch.setitem(sys.modules, name, module)

    def _entrypoint(self, gate_id: str, intents: list[str]) -> Any:
        def run(ctx: GateContext) -> GateResult:
            self.calls.append((gate_id, ctx.head_sha, ctx.order_id))
            passed = gate_id not in self.failing
            word = "pass" if passed else "FAIL"
            return GateResult(
                gate_id=gate_id,
                passed=passed,
                messages=[f"sentinel {word} {gate_id}"],
                intent_ids=intents,
            )

        return run

    @property
    def ids(self) -> set[str]:
        return {g.id for g in self.gates}


def clean_pair(repo: RepoBuilder) -> BaseHeadPair:
    return repo.base_head_pair(
        {}, {f"{ORDER_DIR}/order.yaml": yaml_text(order(ORDER_ID))}, head_branch=f"wo/{ORDER_ID}"
    )


def second_failing_gate() -> str:
    others = sorted(
        g.id for g in load_registry().gates if g.hook_twin_of is None and g.id != IMMUTABLE
    )
    assert others, "the registry needs a second CI gate"
    return others[0]


def test_gate_run_calls_every_entrypoint_and_reports_what_each_returned(
    repo: RepoBuilder,
    factory_cli: FactoryCli,
    identity: FakeIdentity,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    failing = {IMMUTABLE, second_failing_gate()}
    gates = RecordedGates(monkeypatch, failing)
    pair = clean_pair(repo)
    result = gate_run(factory_cli, repo, pair)
    assert_exit(result, exit_codes.GATE_FAILURE)
    assert sorted(call[0] for call in gates.calls) == sorted(gates.ids), gates.calls
    assert {(head, oid) for _, head, oid in gates.calls} == {(pair.head_sha, ORDER_ID)}
    body = report(result)
    for gate_id in gates.ids:
        reported = entry(body, gate_id)
        expected = "fail" if gate_id in failing else "pass"
        assert reported.get("outcome") == expected, reported
        word = "FAIL" if gate_id in failing else "pass"
        assert f"sentinel {word} {gate_id}" in reported.get("messages", []), reported


def test_gate_run_exit_0_only_when_every_entrypoint_passed(
    repo: RepoBuilder,
    factory_cli: FactoryCli,
    identity: FakeIdentity,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    gates = RecordedGates(monkeypatch, failing=set())
    result = gate_run(factory_cli, repo, clean_pair(repo))
    assert_exit(result, exit_codes.OK)
    assert sorted(call[0] for call in gates.calls) == sorted(gates.ids), gates.calls
    body = report(result)
    assert {g.get("id"): g.get("outcome") for g in body.get("gates", [])} == dict.fromkeys(
        gates.ids, "pass"
    )


def test_gate_run_exit_1_on_unoverridden_failure(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    result = gate_run(factory_cli, repo, immutable_violation(repo), IMMUTABLE)
    assert_exit(result, exit_codes.GATE_FAILURE)
    gate = entry(report(result), IMMUTABLE)
    assert gate["outcome"] == "fail", gate
    assert any(OTHER_ORDER in line for line in gate.get("messages", [])), gate


def test_gate_run_reports_results_per_intent(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    result = gate_run(factory_cli, repo, immutable_violation(repo), IMMUTABLE)
    body = report(result)
    intents = body.get("intents", {})
    assert {"gate": IMMUTABLE, "outcome": "fail"} in intents.get("I-M2", []), intents


def test_gate_run_prints_per_intent_lines(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    result = gate_run(factory_cli, repo, immutable_violation(repo), IMMUTABLE, as_json=False)
    assert_exit(result, exit_codes.GATE_FAILURE)
    lines = result.stdout.splitlines()
    assert any("I-M2" in line and IMMUTABLE in line and "fail" in line for line in lines), lines


def test_gate_run_exit_0_when_selected_gates_pass(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = repo.base_head_pair(
        {}, {f"{ORDER_DIR}/order.yaml": yaml_text(order(ORDER_ID))}, head_branch=f"wo/{ORDER_ID}"
    )
    result = gate_run(factory_cli, repo, pair, IMMUTABLE, "bus.schema")
    assert_exit(result, exit_codes.OK)
    body = report(result)
    assert entry(body, IMMUTABLE)["outcome"] == "pass"
    assert entry(body, "bus.schema")["outcome"] == "pass"


# --- override resolution: drift ------------------------------------------------------------


@pytest.mark.parametrize("actor", ["orchestrator", "governor"])
def test_drift_override_with_reason_passes_and_is_surfaced(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity, actor: str
) -> None:
    pair = immutable_violation(repo, override(1, IMMUTABLE, actor=actor))
    result = gate_run(factory_cli, repo, pair, IMMUTABLE)
    assert_exit(result, exit_codes.OK)
    body = report(result)
    gate = entry(body, IMMUTABLE)
    assert gate["outcome"] == "overridden", gate
    assert gate["override"]["reason"] == REASON, gate
    assert gate["override"]["actor"] == actor, gate
    assert body.get("override_counts", {}).get(IMMUTABLE) == 1, body


def test_overridden_gate_text_names_the_reason(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo, override(1, IMMUTABLE))
    result = gate_run(factory_cli, repo, pair, IMMUTABLE, as_json=False)
    assert_exit(result, exit_codes.OK)
    assert f"overridden: {REASON}" in result.stdout, result.stdout


def test_worker_override_is_not_honored(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo, override(1, IMMUTABLE, actor="worker"))
    result = gate_run(factory_cli, repo, pair, IMMUTABLE)
    assert_exit(result, exit_codes.GATE_FAILURE)
    assert entry(report(result), IMMUTABLE)["outcome"] == "fail"


def test_override_for_another_gate_is_not_honored(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo, override(1, "red-first-proof"))
    result = gate_run(factory_cli, repo, pair, IMMUTABLE)
    assert_exit(result, exit_codes.GATE_FAILURE)


def test_override_in_another_orders_folder_is_not_honored(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    stray = message("override", order_id=OTHER, gate=IMMUTABLE, reason=REASON)
    pair = immutable_violation(repo, stray, order_dir=f"bus/orders/{OTHER}")
    result = gate_run(factory_cli, repo, pair, IMMUTABLE)
    assert_exit(result, exit_codes.GATE_FAILURE)


def test_override_counts_every_override_of_a_gate(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo, override(1, IMMUTABLE), override(2, IMMUTABLE))
    result = gate_run(factory_cli, repo, pair, IMMUTABLE)
    assert_exit(result, exit_codes.OK)
    assert report(result).get("override_counts", {}).get(IMMUTABLE) == 2


# --- override resolution: governor-only -----------------------------------------------------


def test_governor_only_gate_fails_without_override(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    result = gate_run(factory_cli, repo, open_od_violation(repo), OPEN_OD)
    assert_exit(result, exit_codes.GATE_FAILURE)
    assert entry(report(result), OPEN_OD)["outcome"] == "fail"


def test_governor_only_gate_ignores_orchestrator_override_labelled_drift(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    """The registry class decides, not the class written in the override."""
    pair = open_od_violation(repo, override(1, OPEN_OD, gate_class="drift"))
    result = gate_run(factory_cli, repo, pair, OPEN_OD)
    assert_exit(result, exit_codes.GATE_FAILURE)
    assert entry(report(result), OPEN_OD)["outcome"] == "fail"


def test_governor_override_honored_unverified_in_recorded_mode(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    gov = override(1, OPEN_OD, actor="governor", gate_class="governor-only")
    result = gate_run(factory_cli, repo, open_od_violation(repo, gov), OPEN_OD)
    assert_exit(result, exit_codes.OK)
    gate = entry(report(result), OPEN_OD)
    assert gate["outcome"] == "overridden", gate
    assert gate["override"]["verified"] is False, gate


def test_governor_override_needs_verified_identity_in_verified_mode(
    verified_repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    gov = override(1, OPEN_OD, actor="governor", gate_class="governor-only")
    pair = open_od_violation(verified_repo, gov)
    result = gate_run(factory_cli, verified_repo, pair, OPEN_OD)
    assert_exit(result, exit_codes.GATE_FAILURE)
    assert entry(report(result), OPEN_OD)["outcome"] == "fail"
    assert identity.asked == [gov["id"]]


def test_governor_override_honored_when_identity_verifies(
    verified_repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    identity.verified = True
    gov = override(1, OPEN_OD, actor="governor", gate_class="governor-only")
    pair = open_od_violation(verified_repo, gov)
    result = gate_run(factory_cli, verified_repo, pair, OPEN_OD)
    assert_exit(result, exit_codes.OK)
    gate = entry(report(result), OPEN_OD)
    assert gate["outcome"] == "overridden", gate
    assert gate["override"]["verified"] is True, gate


# --- --pr: order from the PR head, one commit status per gate --------------------------------


def statuses(github: FakeGitHub, sha: str) -> dict[str, Any]:
    return {status.context: status for status in github.list_commit_statuses(sha)}


def test_gate_run_pr_posts_one_status_per_gate(
    repo: RepoBuilder, factory_cli: FactoryCli, fake_github: FakeGitHub, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo, override(1, IMMUTABLE))
    pr = repo.make_pr(pair.head_branch)
    result = factory_cli(
        "gate",
        "run",
        "--gate",
        IMMUTABLE,
        "--gate",
        OPEN_OD,
        "--pr",
        str(pr.number),
        "--json",
        repo=repo.path,
    )
    assert_exit(result, exit_codes.OK)
    posted = statuses(fake_github, pair.head_sha)
    assert set(posted) == {f"factory/{IMMUTABLE}", f"factory/{OPEN_OD}"}, posted
    overridden = posted[f"factory/{IMMUTABLE}"]
    assert overridden.state == "success", overridden
    assert overridden.description.startswith("overridden: "), overridden
    assert posted[f"factory/{OPEN_OD}"].state == "success"


def test_gate_run_pr_posts_failure_and_resolves_order_from_head(
    repo: RepoBuilder, factory_cli: FactoryCli, fake_github: FakeGitHub, identity: FakeIdentity
) -> None:
    pair = open_od_violation(repo)
    pr = repo.make_pr(pair.head_branch)
    result = factory_cli("gate", "run", "--gate", OPEN_OD, "--pr", str(pr.number), repo=repo.path)
    assert_exit(result, exit_codes.GATE_FAILURE)
    posted = statuses(fake_github, pair.head_sha)
    assert posted[f"factory/{OPEN_OD}"].state == "failure", posted


# --- factory override -----------------------------------------------------------------------


def override_cli(factory_cli: FactoryCli, repo: RepoBuilder, gate: str, *extra: str) -> CliResult:
    return factory_cli(
        "override",
        ORDER_ID,
        "--gate",
        gate,
        "--reason",
        REASON,
        "--pr",
        "1",
        *extra,
        repo=repo.path,
    )


def read_yaml(path: Path) -> dict[str, Any]:
    assert path.is_file(), f"{path} was not written"
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(data, dict), data
    return data


def test_override_cli_writes_numbered_messages_with_registry_class(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo)
    repo.checkout(pair.head_branch)
    first = override_cli(factory_cli, repo, IMMUTABLE, "--actor-model", "claude-opus-5.5")
    second = override_cli(factory_cli, repo, IMMUTABLE, "--actor-model", "claude-opus-5.5")
    assert_exit(first, exit_codes.OK)
    assert_exit(second, exit_codes.OK)
    one = read_yaml(repo.path / ORDER_DIR / "override-01.yaml")
    two = read_yaml(repo.path / ORDER_DIR / "override-02.yaml")
    assert (one["id"], two["id"]) == (f"{ORDER_ID}.override-01", f"{ORDER_ID}.override-02")
    assert one["gate"] == IMMUTABLE and one["gate_class"] == "drift", one
    assert one["actor"] == "orchestrator" and one["reason"] == REASON, one
    repo.commit("overrides")
    result = gate_run(
        factory_cli, repo, BaseHeadPair(pair.base_sha, repo.head_sha(), pair.head_branch), IMMUTABLE
    )
    assert_exit(result, exit_codes.OK)
    assert report(result).get("override_counts", {}).get(IMMUTABLE) == 2


def test_override_cli_governor_on_governor_only_gate(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = open_od_violation(repo)
    repo.checkout(pair.head_branch)
    result = override_cli(factory_cli, repo, OPEN_OD, "--actor", "governor")
    assert_exit(result, exit_codes.OK)
    written = read_yaml(repo.path / ORDER_DIR / "override-01.yaml")
    assert written["actor"] == "governor" and written["gate_class"] == "governor-only", written


def test_override_cli_rejects_unregistered_gate(
    repo: RepoBuilder, factory_cli: FactoryCli, identity: FakeIdentity
) -> None:
    pair = immutable_violation(repo)
    repo.checkout(pair.head_branch)
    result = override_cli(factory_cli, repo, "no-such-gate", "--actor-model", "claude-opus-5.5")
    assert result.exit_code != exit_codes.OK, result
    assert "no-such-gate" in result.stdout + result.stderr, result
    assert not (repo.path / ORDER_DIR / "override-01.yaml").exists()


# --- T059: the workflow is authoritative ------------------------------------------------------


# Steps are judged by what the shell would execute, not by text: each `run` block is
# tokenized (comments, quoting and operators honored) into simple commands. GitHub
# expressions are substituted first, as the runner does.

PR_NUMBER = "42"
EXPRESSIONS = {"github.event.number": PR_NUMBER, "github.event.pull_request.number": PR_NUMBER}
GATE_ARGV = ["factory", "gate", "run", "--pr", PR_NUMBER]
SEPARATORS = {"&&", "||", ";", "|", "&", "\n", "(", ")"}
REDIRECTS = {">", ">>"}
SUMMARY_FILES = {"$GITHUB_STEP_SUMMARY", "${GITHUB_STEP_SUMMARY}"}
UV_OPTIONS_WITH_VALUE = {"--project", "--directory", "--python", "--with", "--group", "--extra"}


def substitute_expressions(run: str) -> str:
    def value(match: re.Match[str]) -> str:
        return EXPRESSIONS.get(match.group(1).strip(), "EXPR")

    return re.sub(r"\$\{\{(.*?)\}\}", value, run)


def shell_commands(run: str) -> list[tuple[list[str], list[str]]]:
    """Simple commands in a `run` block, each as (argv, separator that follows it)."""
    text = substitute_expressions(run).replace("\\\n", " ")
    commands: list[tuple[list[str], list[str]]] = []
    for line in text.splitlines():
        lexer = shlex.shlex(line, posix=True, punctuation_chars=";&|()<>")
        lexer.whitespace_split = True
        lexer.commenters = "#"
        current: list[str] = []
        for token in lexer:
            if token in SEPARATORS:
                if current:
                    commands.append((current, [token]))
                current = []
            else:
                current.append(token)
        if current:
            commands.append((current, ["\n"]))
    return commands


def program_argv(tokens: list[str]) -> list[str]:
    """Drop env assignments, a `uv run [options]` prefix and redirections."""
    argv: list[str] = []
    skip = False
    for token in tokens:
        if skip:
            skip = False
            continue
        if token in REDIRECTS or token == "<":
            skip = True
            continue
        argv.append(token)
    while argv and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*=.*", argv[0]):
        argv = argv[1:]
    if argv[:2] == ["uv", "run"]:
        rest = argv[2:]
        while rest and rest[0].startswith("-"):
            option = rest.pop(0)
            if option in UV_OPTIONS_WITH_VALUE and "=" not in option:
                rest = rest[1:]
        argv = rest
    return argv


def redirects_to_summary(tokens: list[str]) -> bool:
    return any(
        token in REDIRECTS and nxt in SUMMARY_FILES
        for token, nxt in zip(tokens, tokens[1:], strict=False)
    )


def runs_gate_with_own_status(run: str) -> bool:
    """The block is exactly `factory gate run --pr <n>`: its exit status is the step's."""
    commands = shell_commands(run)
    return len(commands) == 1 and program_argv(commands[0][0]) == GATE_ARGV


def mentions_gate_run(run: str) -> bool:
    return any(program_argv(argv)[:3] == GATE_ARGV[:3] for argv, _ in shell_commands(run) if argv)


def publishes_status_to_summary(run: str) -> bool:
    """`factory status` stdout goes to the summary: redirected, or piped into `tee -a`."""
    commands = shell_commands(run)
    for index, (argv, after) in enumerate(commands):
        if program_argv(argv)[:2] != ["factory", "status"]:
            continue
        if redirects_to_summary(argv):
            return True
        if after == ["|"] and index + 1 < len(commands):
            tee = commands[index + 1][0]
            if tee[:1] == ["tee"] and {"-a", "--append"} & set(tee) and SUMMARY_FILES & set(tee):
                return True
    return False


GATE_NO_OPS = [
    "echo 'factory gate run --pr ${{ github.event.number }}'",
    "# factory gate run --pr ${{ github.event.number }}",
    'true "factory gate run --pr ${{ github.event.number }}"',
    "uv run --project scripts/factory factory gate run --pr ${{ github.event.number }} || true",
    "uv run --project scripts/factory factory gate run --pr ${{ github.event.number }}; exit 0",
    "uv run --project scripts/factory factory gate run --pr ${{ github.event.number }} | tee log",
    "set +e\nuv run --project scripts/factory factory gate run --pr ${{ github.event.number }}",
    "uv run --project scripts/factory factory gate run --pr 1",
]
GATE_REAL = "uv run --project scripts/factory factory gate run --pr ${{ github.event.number }}"

SUMMARY_NO_OPS = [
    "echo 'factory status' >> \"$GITHUB_STEP_SUMMARY\"",
    "echo factory status >> $GITHUB_STEP_SUMMARY",
    "# uv run --project scripts/factory factory status >> $GITHUB_STEP_SUMMARY",
    "uv run --project scripts/factory factory status",
    "factory status > /dev/null; echo board >> $GITHUB_STEP_SUMMARY",
    "uv run --project scripts/factory factory status | tee board.md",
    'echo "uv run --project scripts/factory factory status >> $GITHUB_STEP_SUMMARY"',
]
SUMMARY_REAL = [
    'uv run --project scripts/factory factory status >> "$GITHUB_STEP_SUMMARY"',
    "uv run --project scripts/factory factory status | tee -a $GITHUB_STEP_SUMMARY",
]


def gates_job() -> dict[str, Any]:
    workflow = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    job = workflow["jobs"]["factory-gates"]
    assert isinstance(job, dict), job
    return job


def test_workflow_gate_run_on_the_pr_is_not_allowed_to_fail() -> None:
    for run in GATE_NO_OPS:
        assert not runs_gate_with_own_status(run), f"oracle accepts a no-op: {run!r}"
    assert runs_gate_with_own_status(GATE_REAL)
    job = gates_job()
    assert "continue-on-error" not in job, job
    steps = job.get("steps", [])
    gate_steps = [s for s in steps if mentions_gate_run(s.get("run", ""))]
    assert len(gate_steps) == 1, f"expected one `factory gate run` step: {gate_steps}"
    (step,) = gate_steps
    assert runs_gate_with_own_status(step["run"]), (
        f"the gate step must be exactly `factory gate run --pr <event number>`: {step['run']!r}"
    )
    assert "if" not in step, step
    assert step.get("shell", "bash") == "bash", step
    for each in steps:
        assert "continue-on-error" not in each, each


def test_workflow_can_post_commit_statuses() -> None:
    assert gates_job().get("permissions", {}).get("statuses") == "write"


def test_workflow_publishes_the_board_in_the_job_summary() -> None:
    for run in SUMMARY_NO_OPS:
        assert not publishes_status_to_summary(run), f"oracle accepts a no-op: {run!r}"
    for run in SUMMARY_REAL:
        assert publishes_status_to_summary(run), f"oracle rejects a real summary: {run!r}"
    steps = gates_job().get("steps", [])
    summary = [i for i, s in enumerate(steps) if publishes_status_to_summary(s.get("run", ""))]
    assert len(summary) == 1, f"expected one step writing `factory status` to the summary: {steps}"
    gate = [i for i, s in enumerate(steps) if mentions_gate_run(s.get("run", ""))]
    assert gate, steps
    step = steps[summary[0]]
    condition = str(step.get("if", ""))
    runs_after_failure = "always()" in condition or "!cancelled()" in condition
    assert summary[0] < gate[0] or runs_after_failure, (
        f"the board must be published even when the gates fail: {step}"
    )
